/* NestedX.svelte generated by Svelte v3.16.7 */
import {
	SvelteElement,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "./svelte/internal.js";
import { createEventDispatcher, onMount } from "./svelte/svelte.js";

function create_fragment(ctx) {
	let p;

	return {
		c() {
			p = element("p");
			p.textContent = "...or, this one...";
			this.c = noop;
		},
		m(target, anchor) {
			insert(target, p, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

class NestedX extends SvelteElement {
	constructor(options) {
		super();
		init(this, { target: this.shadowRoot }, null, create_fragment, safe_not_equal, {});

		if (options) {
			if (options.target) {
				insert(options.target, this, options.anchor);
			}
		}
	}
}

export default NestedX;
window.customElements.define('nestedx-component', NestedX);