/* slackSection.svelte generated by Svelte v3.12.1 */
import {
	SvelteElement,
	attr,
	binding_callbacks,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space
} from "./svelte/internal.js";
import { createEventDispatcher, onMount } from "./svelte/svelte.js";

function create_fragment(ctx) {
	var link0, t0, link1, t1, link2, t2, div;

	return {
		c() {
			link0 = element("link");
			t0 = space();
			link1 = element("link");
			t1 = space();
			link2 = element("link");
			t2 = space();
			div = element("div");
			div.textContent = "xxxx";
			this.c = noop;
			attr(link0, "href", "https://unpkg.com/tonysoft@1.55.21/css/rollup-slack_kit_base.css");
			attr(link0, "rel", "stylesheet");
			attr(link0, "type", "text/css");
			attr(link1, "href", "https://unpkg.com/tonysoft@1.55.21/css/slackBlockKit.css");
			attr(link1, "rel", "stylesheet");
			attr(link1, "type", "text/css");
			attr(link2, "href", "https://unpkg.com/tonysoft@1.55.21/css/slackBlockKitBuilder.css");
			attr(link2, "rel", "stylesheet");
			attr(link2, "type", "text/css");
		},

		m(target, anchor) {
			insert(target, link0, anchor);
			insert(target, t0, anchor);
			insert(target, link1, anchor);
			insert(target, t1, anchor);
			insert(target, link2, anchor);
			insert(target, t2, anchor);
			insert(target, div, anchor);
			ctx.div_binding(div);
		},

		p: noop,
		i: noop,
		o: noop,

		d(detaching) {
			if (detaching) {
				detach(link0);
				detach(t0);
				detach(link1);
				detach(t1);
				detach(link2);
				detach(t2);
				detach(div);
			}

			ctx.div_binding(null);
		}
	};
}

let markup = '<div class="p-block_kit_renderer__block_wrapper"><div data-qa="bk_section_block" class="p-section_block p-section_block--no_top_margin"><div class="p-section_block_text_content"><div class="p-section_block__text"><div class="p-mrkdwn_element"><span dir="auto">This is a mrkdwn section block <span role="img" aria-label="ghost emoji" class="emoji emoji-sizer" data-codepoints="1f47b" delay="300" aria-describedby="slack-kit-tooltip" style="background-image: url(&quot;https://a.slack-edge.com/37d58/img/emoji_2017_12_06/apple/1f47b.png&quot;);">:ghost:</span> <b data-stringify-prefix="*" data-stringify-suffix="*" data-stringify-requires-siblings="true">this is bold</b>, and <strike data-stringify-prefix="~" data-stringify-suffix="~" data-stringify-requires-siblings="true">this is crossed out</strike>, and <a target="_blank" class="c-link" href="https://slack-redir.net/link?url=https%3A%2F%2Fgoogle.com" rel="noopener noreferrer">this is a link</a></span></div></div></div></div></div>';

function instance($$self, $$props, $$invalidate) {
	let sectionMarkup;

	onMount(() => {
        setTimeout(function() {
            $$invalidate('sectionMarkup', sectionMarkup.innerHTML = markup, sectionMarkup);
        });
		return () => {
		};
	});

	function div_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			$$invalidate('sectionMarkup', sectionMarkup = $$value);
		});
	}

	return { sectionMarkup, div_binding };
}

class slackSection extends SvelteElement {
	constructor(options) {
		super();

		this.shadowRoot.innerHTML = `<style>*{font-family:Slack-Lato, appleLogo, sans-serif}</style>`;

		init(this, { target: this.shadowRoot }, instance, create_fragment, safe_not_equal, []);

		if (options) {
			if (options.target) {
				insert(options.target, this, options.anchor);
			}
		}
	}
}

export default slackSection;
window.customElements.define('slack-section', slackSection);